import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  ArchiveIcon,
  GitHubLogoIcon,
  InstagramLogoIcon,
  TwitterLogoIcon,
  DiscordLogoIcon,
} from '@radix-ui/react-icons'

// generated by v0.dev

export const Footer = () => (
  <footer className='mt-12 border-t py-12 md:py-24 lg:py-32'>
    <div className='container px-4 md:px-6'>
      <div className='grid grid-cols-1 gap-6 md:grid-cols-[1fr_1fr_1fr_1fr] lg:grid-cols-[1fr_1fr_1fr_1fr_1fr_1fr] lg:gap-12'>
        <div className='space-y-4'>
          <div className='flex items-center gap-2'>
            <ArchiveIcon className='h-6 w-6' />
            <h3 className='text-lg font-bold'>Shop Inc</h3>
          </div>
          <p className='text-sm text-secondary-foreground dark:text-gray-400'>
            We provide high-quality clothing and accessories for men, women.
          </p>
        </div>
        <div className='space-y-4'>
          <h3 className='text-lg font-bold'>Useful Links</h3>
          <ul className='grid gap-2'>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                About Us
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Contact Us
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                FAQ
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Shipping & Returns
              </Link>
            </li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h3 className='text-lg font-bold'>Categories</h3>
          <ul className='grid gap-2'>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Men
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Women
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Accessories
              </Link>
            </li>
            <li>
              <Link
                className='text-sm underline-offset-4 hover:underline'
                href='#'
              >
                Collections
              </Link>
            </li>
          </ul>
        </div>
        <div className='space-y-4'>
          <h3 className='text-lg font-bold'>Follow Us</h3>
          <div className='flex gap-4'>
            <Link
              className='text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50'
              href='#'
            >
              <GitHubLogoIcon className='h-5 w-5' />
            </Link>
            <Link
              className='text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50'
              href='#'
            >
              <InstagramLogoIcon className='h-5 w-5' />
            </Link>
            <Link
              className='text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50'
              href='#'
            >
              <TwitterLogoIcon className='h-5 w-5' />
            </Link>
            <Link
              className='text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50'
              href='#'
            >
              <DiscordLogoIcon className='h-5 w-5' />
            </Link>
          </div>
        </div>
        <div className='space-y-4 md:col-span-2'>
          <h3 className='text-lg font-bold'>Newsletter</h3>
          <form className='flex space-x-2'>
            <Input
              className='max-w-lg flex-1'
              placeholder='Enter your email'
              type='email'
            />
            <Button type='submit'>Subscribe</Button>
          </form>
        </div>
      </div>
    </div>
  </footer>
)
